name = "iiif-proxy"
main = "src/index.ts"
compatibility_date = "2026-03-21"

[vars]
# Public variables go here, but NOT the PROXY_SECRET
ALLOWED_ORIGIN = "https://iiif.lfod.top"

[[routes]]
pattern = "iiif-proxy.lfod.top/*"
custom_domain = true
