name = "iiif-proxy"
main = "index.ts"
compatibility_date = "2026-03-21"
workers_dev = true

[vars]
# Public variables go here, but NOT the PROXY_SECRET
ALLOWED_ORIGIN = "https://iiif.lfod.top"

[[routes]]
pattern = "iiif-proxy.lfod.top/*"
zone_id = "13cd2861f316a2eac0993944ade3ae88"
